install.packages('plyr')
install.packages('tidyverse')
install.packages('magrittr')
install.packages('reshape2')
install.packages('fs')
install.packages('lubridate')
install.packages('kableExtra')
install.packages('knitr')
install.packages('pander')
install.packages('here')
install.packages('redcapAPI')

